# Generated by Django 5.2 on 2025-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_dishtype_options_alter_dish_cooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
